### PR TITLE
Update .nvmrc

### PR DESCRIPTION
**Pull request by lirantal**
The package @travi/any@3.0.0 has a hard requirement on Node.js versions:

```sh
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @travi/any@3.0.0
npm ERR! notsup Not compatible with your version of node/npm: @travi/any@3.0.0
npm ERR! notsup Required: {"node":"^18.17 || >=20.6.1"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.12.1"}
```

### CODE REVIEW

**Comment by travi** [comment]
thanks for the heads up on this, @lirantal!

for the context of this project, i think i'd rather update with a convention change i've made since the last time i gave this project much attention. instead of `engines-strict` in the `.npmrc` (which can be a bit more aggressive than my intention), i've been using [ls-engines](https://www.npmjs.com/package/ls-engines) (which focuses more on engines requirements of consumers of the published package).

**Comment by travi** [comment]
looks like i havent supported an `engines.node` range for this project, so `ls-engines` doesn't apply until i do that. for now, i moved the `.nvmrc` back to the full major version range, but removed the `engines-strict` property from the `.npmrc`.

i'm interested in your thoughts on my changes before i merge, but once we get this moved forward, i'll make a few more changes to the project and define `engines.node` as a breaking change. i'll get `ls-engines` incorporated as part of that update

**Comment by travi** [comment]
btw, sorry that i missed this for a bit. the last few weeks have been pretty busy. i saw recently that youre looking into slide deck frameworks, but i'm curious what brought you here to look at my form8ion plugin. anything i can help you with?

**Comment by lirantal** [comment]
Thanks buddy. I'll take a look. Nothing urgent here. Take care ❤️🤗

**Review by travi — APPROVED** [review]
i'm going to go ahead and merge this. can always adjust further as a follow up

**Pull request merged**
